/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(router_msg_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(67aeb7818de8c967aacaaec7f983f769)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/zeromq/router_msg_sink.h>
// pydoc.h is automatically generated in the build directory
#include <router_msg_sink_pydoc.h>

void bind_router_msg_sink(py::module& m)
{

    using router_msg_sink = ::gr::zeromq::router_msg_sink;


    py::class_<router_msg_sink, gr::block, gr::basic_block, std::shared_ptr<router_msg_sink>>(
        m, "router_msg_sink", D(router_msg_sink))

        .def(py::init(&router_msg_sink::make),
             py::arg("address"),
             py::arg("timeout") = 100,
             py::arg("linger") = 0,
             py::arg("bind") = true,
             D(router_msg_sink, make))


        .def(
            "last_endpoint", &router_msg_sink::last_endpoint, D(router_msg_sink, last_endpoint))

        .def(
            "teardown", &router_msg_sink::teardown, D(router_msg_sink, teardown))

        ;
}
